if [ -d "$HOME/.cargo" ]; then
  . "$HOME/.cargo/env"
fi

if [ -e /home/marcogomez/.nix-profile/etc/profile.d/nix.sh ]; then . /home/marcogomez/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
