#!/bin/bash

SESSION="◕_◕"

# Check if the session already exists, and create it if it doesn't
if ! tmux has-session -t $SESSION 2>/dev/null; then
  tmux new-session -d -s $SESSION -n SYS
  tmux send-keys -t $SESSION:0 "btop" C-m
  tmux rename-window -t $SESSION:0 SYS
  tmux set-window-option -t $SESSION:0 automatic-rename off

  tmux new-window -t $SESSION:1 -n TTY0
  tmux rename-window -t $SESSION:1 TTY0
  tmux set-window-option -t $SESSION:1 automatic-rename off

  tmux new-window -t $SESSION:2 -n TTY1
  tmux rename-window -t $SESSION:2 TTY1
  tmux set-window-option -t $SESSION:2 automatic-rename off

  tmux select-window -t $SESSION:2
fi

# Attach to the session
tmux attach -t $SESSION
